server:
  port: 9090
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stats-db
    username: stats
    password: stats
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: "true"
    show-sql: "true"
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: DEBUG
        transaction:
          interceptor: DEBUG
          nodeValue: DEBUG