stats-server:
  name: ewm-service
  url: http://stats-service-container:9090
server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm-db
    username: ewm
    password: ewm
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: "true"
    show-sql: "true"
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: DEBUG
        transaction:
          interceptor: DEBUG
          nodeValue: DEBUG