CREATE TABLE IF NOT EXISTS users (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name  VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name  VARCHAR(50) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id),
  CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    initiator_id       BIGINT NOT NULL,
    annotation         VARCHAR(2000) NOT NULL,
    title              VARCHAR(255) NOT NULL,
    description        TEXT NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    category_id        BIGINT NOT NULL,
    lat                REAL NOT NULL,
    lon                REAL NOT NULL,
    confirmed_requests BIGINT DEFAULT 0,
    paid               BOOL DEFAULT FALSE,
    participant_limit  BIGINT DEFAULT 0,
    state              VARCHAR(32) NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOL DEFAULT TRUE,
    views              BIGINT DEFAULT 0,
    CONSTRAINT pk_event PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT NOT NULL,
    event_id     BIGINT NOT NULL,
    status       VARCHAR(10) NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT uq_requester_event UNIQUE (requester_id, event_id),
    FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(255) NOT NULL,
    pinned  BOOL NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_compilations PRIMARY KEY (id),
    CONSTRAINT uq_compilations_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       BIGINT REFERENCES events (id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);